apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Name }}
spec:
  hosts:
    {{ if .Values.ingress.hosts}}
    {{- range $.Values.ingress.hosts }}
    {{- range .hosts }}
    - {{ . | default "- '*'" }}
    {{- end }}
    {{- end }}
    {{ else }}
    - "*"
    {{ end }}
  gateways:
    - {{ .Chart.Name }}
  http:
    - match:
        - uri:
            prefix: {{ .Values.ingress.path }}
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ .Chart.Name }}
            port:
              number: 80
      retries:
        attempts: 5
        perTryTimeout: 30s